---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: retro-board
  labels:
    name: app
    app: app
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
        app: app
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: app
          image: containers.chewed-k8s.net/retro-board/app:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: NEXTAUTH_URL
              value: https://retro-board.it
            - name: NEXTAUTH_URL_INTERNAL
              value: https://$(DASHBOARD_PORT_3000_TCP_ADDR)
            - name: NEXT_PUBLIC_FLAGS_AGENT
              value: 281f691b-f932-4d50-8fce-4bdf037fe6cb
            - name: NEXT_PUBLIC_FLAGS_PROJECT
              value: ce70ace8-9516-4c18-ae62-1f9b1b1d2b33
            - name: NEXT_PUBLIC_FLAGS_ENVIRONMENT
              value: cd76e6a2-95da-4b5d-b129-b6f3b26b2ebf
            - name: KEYCLOAK_ISSUER
              value: https://keycloak.chewed-k8s.net/realms/retro-board
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"

---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: retro-board
  labels:
    name: app
    app: app
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: retro-board
  annotations:
    cert-manager.io/cluster-issuer: live-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app: app
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - retro-board.it
        - "*.retro-board.it"
      secretName: app-tls
  rules:
    - host: retro-board.it
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 3000
    - host: "*.retro-board.it"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 3000
